#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '11.0'

use_frameworks!

target 'RecipePuppyChallenge' do
    pod 'SwiftyJSON'
    pod 'RxSwift', '~> 4.0'
    pod 'RxCocoa', '~> 4.0'
    pod 'Alamofire'
end

target 'RecipePuppyChallengeTests' do
    inherit! :search_paths
end
